name: Build Kernel

permissions:
  contents: write
  actions: write

on:
  workflow_call:

jobs:
  
  # Samsung

  build-samsung-note10-oneui-a15:
    name: "Samsung Galaxy Note10 (OneUI A15)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-samsung-note10-oneui-a15.yml
    secrets: inherit

  build-samsung-note10plus-oneui-a15:
    name: "Samsung Galaxy Note10+ (OneUI A15)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build-samsung-note10plus-oneui-a15.yml
    secrets: inherit

  
